#
# Rules of any monitor, window, layer, and etc
#

# window rule
## appid
windowrule=width:800,height:900,isfloating:1,appid:pavucontrol-qt
windowrule=width:800,height:900,isfloating:1,appid:Zoom
windowrule=scroller_portion:1.0,appid:zen
## title
windowrule=width:1600,height:1600,isfloating:1,appid:float


# layer rule
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi
