set -g default-terminal "xterm-kitty"

# for 256 color support
set -ag terminal-overrides ",xterm-kitty:Tc"

# goes to visual mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# move status position to the top
set-option -g status-position top

# shell
set -g default-command "${SHELL}"
set-option -sg escape-time 10
# Enable support for modern terminal keyboard protocols
set-window-option -g xterm-keys on

### Plugins section
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# setting of plugins
set -g @continuum-restore 'on'
set -g @continuum-save-interval '60' # minutes

## Running TPM
run ~/.config/tmux/plugins/tpm/tpm
